In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [2]:
df = pd.read_csv ("final_internship_data.csv")
df.head()

,User ID,User Name,Driver Name,Car Condition,Weather,Traffic Condition,key,fare_amount,pickup_datetime,pickup_longitude,...,month,weekday,year,jfk_dist,ewr_dist,lga_dist,sol_dist,nyc_dist,distance,bearing
0,KHVrEVlD,Kimberly Adams,Amy Butler,Very Good,windy,Congested Traffic,2009-06-15 17:26:21.0000001,4.5,2009-06-15 17:26:21,-1.288826,...,6,0,2009,20.265840,55.176046,14.342611,34.543548,27.572573,1.030764,-2.918897
1,lPxIuEri,Justin Tapia,Hannah Zimmerman,Excellent,cloudy,Flow Traffic,2010-01-05 16:52:16.0000002,16.9,2010-01-05 16:52:16,-1.291824,...,1,1,2010,44.667679,31.832358,23.130775,15.125872,8.755732,8.450134,-0.375217
2,gsVN8JLS,Elizabeth Lopez,Amanda Jackson,Bad,stormy,Congested Traffic,2011-08-18 00:35:00.00000049,5.7,2011-08-18 00:35:00,-1.291242,...,8,3,2011,43.597686,33.712082,19.865289,17.722624,9.847344,1.389525,2.599961
3,9I7kWFgd,Steven Wilson,Amy Horn,Very Good,stormy,Flow Traffic,2012-04-21 04:30:42.0000001,7.7,2012-04-21 04:30:42,-1.291319,...,4,5,2012,42.642965,32.556289,21.063132,15.738963,7.703421,2.799270,0.133905
4,8QN5ZaGN,Alexander Andrews,Cassandra Larson,Bad,stormy,Congested Traffic,2010-03-09 07:51:00.000000135,5.3,2010-03-09 07:51:00,-1.290987,...,3,1,2010,43.329953,39.406828,15.219339,23.732406,15.600745,1.999157,-0.502703

In [3]:
df.duplicated().sum()

0

In [4]:
df.drop(columns=['User ID', 'User Name', 'Driver Name', 'key', 'pickup_datetime'], inplace=True)
df.head()

,Car Condition,Weather,Traffic Condition,fare_amount,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count,hour,...,month,weekday,year,jfk_dist,ewr_dist,lga_dist,sol_dist,nyc_dist,distance,bearing
0,Very Good,windy,Congested Traffic,4.5,-1.288826,0.710721,-1.288779,0.710563,1,17,...,6,0,2009,20.265840,55.176046,14.342611,34.543548,27.572573,1.030764,-2.918897
1,Excellent,cloudy,Flow Traffic,16.9,-1.291824,0.710546,-1.291182,0.711780,1,16,...,1,1,2010,44.667679,31.832358,23.130775,15.125872,8.755732,8.450134,-0.375217
2,Bad,stormy,Congested Traffic,5.7,-1.291242,0.711418,-1.291391,0.711231,2,0,...,8,3,2011,43.597686,33.712082,19.865289,17.722624,9.847344,1.389525,2.599961
3,Very Good,stormy,Flow Traffic,7.7,-1.291319,0.710927,-1.291396,0.711363,1,4,...,4,5,2012,42.642965,32.556289,21.063132,15.738963,7.703421,2.799270,0.133905
4,Bad,stormy,Congested Traffic,5.3,-1.290987,0.711536,-1.290787,0.711811,1,7,...,3,1,2010,43.329953,39.406828,15.219339,23.732406,15.600745,1.999157,-0.502703

In [5]:
# Drop rows with invalid fare amounts
df = df[(df['fare_amount'] >= 0.5) & (df['fare_amount'] <= 300)]

print(f"Number of rows after dropping invalid fare amounts: {len(df)}")

Number of rows after dropping invalid fare amounts: 499953

In [6]:
# Drop rows with invalid fare amounts
df = df[(df['distance'] >= 0.5) & (df['distance'] <= 100)]

print(f"Number of rows after dropping invalid fare amounts: {len(df)}")

Number of rows after dropping invalid fare amounts: 469658

In [7]:
df.shape

(469658, 21)

In [8]:
df.duplicated().sum()

0

In [9]:
df = df.dropna()

In [10]:
from sklearn.model_selection import train_test_split

X = df.drop(columns=['fare_amount'])
y = df['fare_amount']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [11]:
from sklearn.preprocessing import LabelEncoder

le_TrafficCondition = LabelEncoder().fit(X_train["Traffic Condition"])
le_Weather = LabelEncoder().fit(X_train["Weather"])
le_CarCondition = LabelEncoder().fit(X_train["Car Condition"])

In [12]:
X_train["Traffic Condition"] = le_TrafficCondition.transform(X_train["Traffic Condition"])
X_train["Weather"] = le_Weather.transform(X_train["Weather"])
X_train["Car Condition"] = le_CarCondition.transform(X_train["Car Condition"])

X_test["Traffic Condition"] = le_TrafficCondition.transform(X_test["Traffic Condition"])
X_test["Weather"] = le_Weather.transform(X_test["Weather"])
X_test["Car Condition"] = le_CarCondition.transform(X_test["Car Condition"])

In [13]:
df.head()

,Car Condition,Weather,Traffic Condition,fare_amount,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count,hour,...,month,weekday,year,jfk_dist,ewr_dist,lga_dist,sol_dist,nyc_dist,distance,bearing
0,Very Good,windy,Congested Traffic,4.5,-1.288826,0.710721,-1.288779,0.710563,1,17,...,6,0,2009,20.265840,55.176046,14.342611,34.543548,27.572573,1.030764,-2.918897
1,Excellent,cloudy,Flow Traffic,16.9,-1.291824,0.710546,-1.291182,0.711780,1,16,...,1,1,2010,44.667679,31.832358,23.130775,15.125872,8.755732,8.450134,-0.375217
2,Bad,stormy,Congested Traffic,5.7,-1.291242,0.711418,-1.291391,0.711231,2,0,...,8,3,2011,43.597686,33.712082,19.865289,17.722624,9.847344,1.389525,2.599961
3,Very Good,stormy,Flow Traffic,7.7,-1.291319,0.710927,-1.291396,0.711363,1,4,...,4,5,2012,42.642965,32.556289,21.063132,15.738963,7.703421,2.799270,0.133905
4,Bad,stormy,Congested Traffic,5.3,-1.290987,0.711536,-1.290787,0.711811,1,7,...,3,1,2010,43.329953,39.406828,15.219339,23.732406,15.600745,1.999157,-0.502703

In [14]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# 2. Columns to scale
columns_to_scale = [
    'pickup_longitude', 'pickup_latitude',
    'dropoff_longitude', 'dropoff_latitude', 'distance',
    'jfk_dist', 'ewr_dist', 'lga_dist', 'sol_dist', 'nyc_dist', 'bearing'
]

# 3. Fit on train only
scaler = StandardScaler()
X_train[columns_to_scale] = scaler.fit_transform(X_train[columns_to_scale])

# 4. Transform test using the same scaler
X_test[columns_to_scale] = scaler.transform(X_test[columns_to_scale])

print(X_train[columns_to_scale].head())
print(X_test[columns_to_scale].head())

        pickup_longitude  pickup_latitude  dropoff_longitude  \
400123         -0.015179         0.028148          -0.015959
52331          -0.024639         0.027973          -0.024140
238658         -0.017204         0.039809          -0.023454
368247         -0.025608         0.028739          -0.017543
252133         -0.029374         0.016805          -0.017512

        dropoff_latitude  distance  jfk_dist  ewr_dist  lga_dist  sol_dist  \
400123          0.032281 -0.678479 -0.023311 -0.016654 -0.031259 -0.016005
52331           0.025994 -0.692142 -0.020877 -0.022951 -0.025274 -0.021583
238658          0.026616  0.221588 -0.019030 -0.017986 -0.027535 -0.015652
368247          0.047842  0.533896 -0.015388 -0.016468 -0.025796 -0.012526
252133          0.027337  0.111452 -0.023702 -0.024060 -0.024696 -0.024599

        nyc_dist   bearing
400123 -0.016825 -0.123858
52331  -0.021954 -1.756424
238658 -0.016011  1.379562
368247 -0.012475 -0.359536
252133 -0.025379 -0.587717
        pickup_longitude  pickup_latitude  dropoff_longitude  \
30291          -0.024071         0.023500          -0.026631
247732         -0.023019         0.026365          -0.023065
49001          -0.024314         0.029928          -0.021898
139364         -0.029009         0.003367          -0.035171
384239         -0.025532         0.026287          -0.028630

        dropoff_latitude  distance  jfk_dist  ewr_dist  lga_dist  sol_dist  \
30291           0.022044 -0.706648 -0.022572 -0.025003 -0.023854 -0.024861
247732          0.021176 -0.459074 -0.023220 -0.023243 -0.025419 -0.023207
49001           0.028087 -0.649056 -0.020411 -0.021435 -0.026338 -0.019679
139364          0.012953 -0.144094 -0.025039 -0.032491 -0.014276 -0.036151
384239         -0.010183  1.902875 -0.026135 -0.026986 -0.015049 -0.028752

        nyc_dist   bearing
30291  -0.025469  1.203333
247732 -0.023929 -1.860090
49001  -0.020023 -1.528236
139364 -0.034788  0.071535
384239 -0.022957  1.513741

In [16]:
import pandas as pd
from statsmodels.stats.outliers_influence import variance_inflation_factor
import numpy as np


X_vif = X_train.copy()


X_vif.replace([np.inf, -np.inf], np.nan, inplace=True)
X_vif.dropna(inplace=True)

vif_data = pd.DataFrame()
vif_data["feature"] = X_vif.columns
vif_data["VIF"] = [variance_inflation_factor(X_vif.values, i) for i in range(X_vif.shape[1])]


vif_data = vif_data.sort_values(by="VIF", ascending=False).reset_index(drop=True)
print(vif_data)

              feature           VIF
0            sol_dist  1.661453e+06
1            nyc_dist  8.795928e+05
2            ewr_dist  4.316550e+05
3            jfk_dist  4.271154e+04
4            lga_dist  3.747118e+04
5    pickup_longitude  7.168735e+03
6   dropoff_longitude  7.147675e+03
7    dropoff_latitude  1.199753e+03
8                year  2.178297e+01
9     pickup_latitude  1.984279e+01
10               hour  5.375825e+00
11              month  4.329077e+00
12                day  4.268916e+00
13            weekday  3.484453e+00
14            Weather  3.004225e+00
15      Car Condition  2.803445e+00
16    passenger_count  2.663553e+00
17  Traffic Condition  2.498989e+00
18           distance  1.816981e+00
19            bearing  1.329921e+00

In [18]:
X_train.drop(columns=['sol_dist', 'nyc_dist', 'ewr_dist', 'lga_dist', 'dropoff_latitude', 'dropoff_longitude', 'pickup_latitude', 'pickup_longitude'], inplace=True)
X_test.drop(columns=['sol_dist', 'nyc_dist', 'ewr_dist', 'lga_dist', 'dropoff_latitude', 'dropoff_longitude', 'pickup_latitude', 'pickup_longitude'], inplace=True)

In [22]:
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
from sklearn.ensemble import RandomForestRegressor

param_grid = {
    'n_estimators': [10, 50, 100],            
    'max_depth': [5, 10, None],            
    'min_samples_split': [2, 5, 10],           
    'min_samples_leaf': [1, 2, 4],             
    'max_features': ['sqrt', 'log2']
}

rf = RandomForestRegressor(random_state=42)
grid = GridSearchCV(estimator=rf, param_grid=param_grid, cv=3, scoring='neg_mean_squared_error', n_jobs=-1, verbose=1)

grid.fit(X_train, y_train)

print("Best Parameters:", grid.best_params_)
print("Best Cross-Validation Accuracy:", grid.best_score_)

Fitting 3 folds for each of 162 candidates, totalling 486 fits
Best Parameters: {'max_depth': None, 'max_features': 'sqrt', 'min_samples_leaf': 2, 'min_samples_split': 2, 'n_estimators': 100}
Best Cross-Validation Accuracy: -11.536915045430504

In [23]:
best_rf = grid.best_estimator_
yPred = best_rf.predict(X_test)

print("\n=== Random Forest Performance on Test Set ===")
print("R² Score:", r2_score(y_test, yPred))
print("Mean Squared Error:", mean_squared_error(y_test, yPred))
print("Mean Absolute Error:", mean_absolute_error(y_test, yPred))

=== Random Forest Performance on Test Set ===
R² Score: 0.8784731404225441
Mean Squared Error: 10.9245995765408
Mean Absolute Error: 1.6724080642578167

In [27]:
import joblib

joblib.dump(best_rf, "best_random_forest_model.pkl")
print("Model saved successfully!")

Model saved successfully!

In [28]:
from xgboost import XGBRegressor
param_grid = {
    'n_estimators': [100, 200, 50],
    'max_depth': [3, 5, 7],
    'min_child_weight': [1, 3, 5],
    'gamma': [0, 0.1, 0.3],
    'colsample_bytree': [0.6, 0.8, 1.0],
    'learning_rate': [0.01, 0.1]
}

xgb = XGBRegressor(
    objective='reg:squarederror',  
    random_state=42
)

grid = GridSearchCV(estimator=xgb, param_grid=param_grid, cv=3, scoring='neg_mean_squared_error', n_jobs=-1, verbose=1)

grid.fit(X_train, y_train)

# Best parameters
print("Best Parameters:", grid.best_params_)
print("Best Cross-Validation R²:", grid.best_score_)

Fitting 3 folds for each of 486 candidates, totalling 1458 fits
Best Parameters: {'colsample_bytree': 1.0, 'gamma': 0.3, 'learning_rate': 0.1, 'max_depth': 7, 'min_child_weight': 3, 'n_estimators': 200}
Best Cross-Validation R²: -10.803744371389591

In [29]:
# Evaluate on test set
best_xgb = grid.best_estimator_
yPred = best_xgb.predict(X_test)

print("\n=== XGB Performance on Test Set ===")
print("R² Score:", r2_score(y_test, yPred))
print("Mean Squared Error:", mean_squared_error(y_test, yPred))
print("Mean Absolute Error:", mean_absolute_error(y_test, yPred))

=== XGB Performance on Test Set ===
R² Score: 0.8842440654099822
Mean Squared Error: 10.405825003633868
Mean Absolute Error: 1.5801879067218

In [30]:
import joblib

joblib.dump(best_xgb, "best_XGB_model.pkl")
print("Model saved successfully!")

Model saved successfully!